### ISSUE TITLE
Send Audio and Have Someone Else open it?

### ISSUE THREAD

**Issue by NL33** [nstudio/nativescript-audio#156]
The documentation is pretty clear on recording audio, but can someone please clarify what you can do with it from there? 

For example:
1) Is there a way to send the audio file somewhere? For example, the nativescript social share plugin allows you to share text and images (via text, email, or other sharing options on the person's phone). Is there a way anywhere to share an audio file you just recorded using nativescript-audio?

2) If someone sends you an audio file, let's say via text. Is there a way to open it in app and play it with this plugin? Right now, most audio files, at least on iOS, seem to open in quicktime by default. Any way to make them open in your app?

**Comment by bradmartin** [comment]
You'd have to save the audio file using the file-system API. That's probably more work involved, because you'd need to know when a file is sent to the device. So to take full control, you'd need to do some sort of file sharing in your app, probably upload it to your backend, send the link to the other device, download the file there and store it using `file-system` and then play it using this plugin. Hope that helps some.
